maurodatamapper:
    security:
        public: false

environments:
    test:
        name: 'mpabTest'
        database.creation: 'CREATE SCHEMA IF NOT EXISTS core\;CREATE SCHEMA IF NOT EXISTS security'